--사용 가능한 데이터 사전 살펴보기
SELECT * FROM DICT;

SELECT * FROM DICTIONARY;

-- 객체 정보 살펴보기
SELECT TABLE_NAME
  FROM USER_TABLES;
  
SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES;
  
-- DBA_접두어 사용하기
SELECT * FROM DBA_TABLES;

SELECT * FROM DBA_TABLES;

--SYS 계정으로
SELECT * FROM DBA_TABLES;

SELECT * 
  FROM DBA_USERS
 WHERE USERNAME = 'SCOTT';
 
--인덱스 정보 알아보기
SELECT *
  FROM USER_INDEXES;
  
--컬럼 정보 알아보기
SELECT *
  FROM USER_IND_COLUMNS;
  
--EMP 테이블의 SAL 열에 인덱스 생성하기
CREATE INDEX IDX_EMP_SAL
    ON EMP(SAL);
    
SELECT * FROM USER_IND_COLUMNS;

--인덱스 삭제하기
DROP INDEX IDX_EMP_SAL;

SELECT * FROM USER_IND_COLUMNS;

GRANT CREATE VIEW TO SCOTT;

--뷰 생성하기
CREATE VIEW VW_EMP20
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO
          FROM EMP
         WHERE DEPTNO = 20);
         
SELECT *
  FROM USER_VIEWS;
  
SELECT VIEW_NAME, TEXT_LENGTH, TEXT
  FROM USER_VIEWS;
 
-- 뷰 조회하기  
SELECT *
  FROM VW_EMP20;
  
--뷰 삭제하기
DROP VIEW VW_EMP20;

--ROWNUM를 추가로 조회하기
SELECT ROWNUM, E.*
  FROM EMP E;
  
--EMP 테이블을 SAL 열 기준으로 정렬하기
SELECT ROWNUM, E.*
  FROM EMP E
 ORDER BY SAL DESC;
 
--인라인 뷰
SELECT ROWNUM, E.*
  FROM (SELECT *
          FROM EMP E
         ORDER BY SAL DESC) E;
         
WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM, E.*
  FROM E;
  
--인라인 뷰로 TOP-N 추출하기
SELECT ROWNUM, E.*
  FROM (SELECT *
          FROM EMP E
         ORDER BY SAL DESC) E
 WHERE ROWNUM <= 3;
 
WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM, E.*
  FROM E
 WHERE ROWNUM <= 3;
 
--DEPT 테이블을 사용하여 DEPT_SEQUENCE 테이블 생성하기
CREATE TABLE DEPT_SEQUENCE
    AS SELECT *
         FROM DEPT
        WHERE 1 <> 1;
        
SELECT * FROM DEPT_SEQUENCE;

--시퀀스 생성하기
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
 INCREMENT BY 10
 START WITH 10
 MAXVALUE 90
 MINVALUE 0
 NOCYCLE
 CACHE 2;
 
SELECT *
  FROM USER_SEQUENCES;
  
--시퀀스에서 생성한 순번을 사용한 INSERT문 실항하기
INSERT INTO DEPT_SEQUENCE ( DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--가장 마지막으로 생성된 시퀀스 확인하기
SELECT SEQ_DEPT_SEQUENCE.CURRVAL
  FROM DUAL;
  
--시퀀스에서 생성한 순번을 반복 사용하여 INSERT 문 실행하기
INSERT INTO DEPT_SEQUENCE ( DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--시퀀스 옵션 수정하기
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
 INCREMENT BY 3
 MAXVALUE 99
 CYCLE;
 
SELECT * 
  FROM USER_SEQUENCES;
  
--수정한 시퀀스를 사욯아여 INSERT문 실행하기
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--시퀀스 삭제후 확인하기
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

SELECT * FROM USER_SEQUENCES;

--테이블 동의어 생성하기
CREATE SYNONYM E
   FOR EMP;
   
SELECT * FROM E;

DROP SYNONYM E;