--15장.사용자, 권한, 롤 관리

--SCOTT 계정으로 사용자 생성하기
CREATE USER ORCLSTUDY
INDENTIFIED BY ORACLE; --오류

--SYSTEM  사용자로 접속 후 사용자 생성하기
CREATE USER ORCLSTUDY
INDENTIFIED BY ORACLE;

--SYSTEM 사용자로 접속 후 ORCLSTUDY 사용자에게 권한 부여하기
GRANT CREATE SESSION TO ORCLSTUDY;

--사용자 정보(패스워드) 변경하기
ALTER USER ORCLSTUDY
IDENNIFIED BY ORCL;

--사용자 삭제하기
DROP USER ORCLSTUDY;

--사용자와 객체 모두 삭제하기
DROP USER ORCLSTUDY CASCADE;

--SYSTEM 계정으로 접속하여 사용자 생성하기
CREATE USER ORCLSTUDY
INDENTIFIED BY ORACLE;

--사용자 권한 부여하기
GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY;

--ORCLSTUDY 사용자에게 TEMP 테이블 권한 부여하기
CONN SCOTT/tiger

CREATE TABLE TEMP(
   COL1 VARCHAR(20),
   COL2 VARCHAR(20)
   );
   
GRANT SELECT ON TEMP TO ORCLSTUDY;

GRANT INSERT ON TEMP TO ORCLSTUDY;

--ORCL에게 TEMP 테이브르이 여러 권한을 한 번에 부여하기
GRANT SELECT, INSERT ON TEMP
   TO ORCLSTUDY;

--ORCLSTUDY로 사용 권한을 부여받은 TEMP 테이블 사용하기
CONN ORCLSTUDY/ORACLE

SELECT * FROM SCOTT.TEMP;

INSERT INTO SCOTT.TEMP VALUES('TEXT', 'FROM ORCLSTUDY');

SELECT * FROM SCOTT.TEMP;

--ORCLSTUDY에 부여된 TEMP 테이블 사용 권한 취소하기
CONN SCOTT/tiger

REVOKE SELECT, INSERT ON TEMP FROM ORCLSTUDY;

--ORCLSTUDY로 권한 철회된 TEMP 테이블 조회하기(실패)
CONN PRCLSTUDY/ORACLE

SELECT * FROM SCOTT.TEMP;

--SYSTEM 계정으로 ROLESTUDY 롤 생성 및 권한 부여하기
CONN SYSTEM/oracle

CREATE ROLE ROLESTUDY;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM
   TO ROLESTUDY;
   
--ORCLSTUDY 사용자에게 롤 부여하기
GRANT ROLESYUDY TO ORCLSTUDY;

--ORCLESTUDY에 부여된 롤과 권한 확인하기
CONN ORCLSTUDY/ORACLE
SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;
