SELECT * FROM EMP,DEPT ORDER BY EMPNO; //FROM절에 여러 테이블 선언하기

SELECT * 
  FROM EMP,DEPT
 WHERE EMP.DEPTNO = DEPT.DEPTNO
 ORDER BY EMPNO;   //열 이름을 비교하는 조건식으로 조인하기
 
SELECT *
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
 ORDER BY EMPNO;   //테이블 이름을 별칭으로 표현하기
 
SELECT EMPNO, ENAME, DEPTNO, DNAME, LOC
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO;  // 두 테이블에 부서 번호가 똑같은 열 이름을 포함되어 있을 때 = 오류발생
 
SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
 ORDER BY D.DEPTNO, E.EMPNO;  // 열 이름에 각각의 테이블 이름도 함께 명시할 때
 
SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND SAL >= 3000;  //WHERE절에 추가로 조건식 넣어 출력하기
   
SELECT *
  FROM EMP E, SALGRADE S
 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;  //급여 범위를 지정하는 조건식으로 조인하기
 
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1, EMP E2
 WHERE E1.MGR = E2.EMPNO;  // 같은 테이블을 두번 사용하여 자체 조인하기
 
--외부조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1, EMP E2
 WHERE E1.MGR = E2.EMPNO(+)
 ORDER BY E1.EMPNO;  //왼쪽 외부 조인 사용하기
 
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1, EMP E2
 WHERE E1.MGR(+) = E2.EMPNO
 ORDER BY E1.EMPNO;  //오른쪽 외부 조인 사용하기
 
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
       DEPTNO, D.DNAME, D.LOC
  FROM EMP E NATURAL JOIN DEPT D
 ORDER BY DEPTNO, E.EMPNO;  //NATURAL JOIN을 사용하여 조인하기 : 두테이블에 이름과 자료형이 같은 열을 찾은 후 그 열을 기준으로 등가 조인
 

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
       DEPTNO, D.DNAME, D.LOC
  FROM EMP E JOIN DEPT D USING (DEPTNO)
 WHERE SAL >= 3000
 ORDER BY DEPTNO, E.EMPNO;  //JOIN ~ USING 을 사용하여 조인하기
 
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
       E.DEPTNO, 
       D.DNAME, D.LOC
  FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
 WHERE SAL <= 3000
 ORDER BY E.DEPTNO, EMPNO;  //JOIN ~ ON으로 등가 조인하기
 
--OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1 LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
 ORDER BY E1.EMPNO;   //왼쪽 외부조인으로 작성하기
 
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1 RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
 ORDER BY E1.EMPNO;   //오른쪽 외부조인으로 작성하기

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1 FULL OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
 ORDER BY E1.EMPNO;   //오른쪽 외부조인으로 작성하기
